CREATE DATABASE BLUFF_CITY DEFAULT CHARACTER SET UTF8 DEFAULT COLLATE UTF8_GENERAL_CI;

USE BLUFF_CITY;

CREATE TABLE user (
	ID VARCHAR(20) PRIMARY KEY NOT NULL,
    PW VARCHAR(20) NOT NULL,
    NICKNAME VARCHAR(10) NOT NULL
);